### ISSUE TITLE
Why is this plugin limited for version up to version 29.0?

### ISSUE THREAD

**Issue by LouisCAD** [jjohannes/missing-metadata-guava#3]
Guava entered the 30.x versions, and AFAIK, there's still no metadata, and the wrong variants keep being selected, so I think it'd make sense to still have this plugin.

**Comment by jjohannes** [comment]
Unfortunately each version has to be handled specifically in the plugin code, because the rule that enriches the metadata only sees one of the _pom_ files. So information that is only in the other _pom_ file needs to be hard coded in the rule.

I completely missed the 30.x release. Thanks for bringing it up. I'll update this plugin to support it.

**Comment by jjohannes** [comment]
Actually, I mixed something up and already added support for 30.x in version `0.3`. (https://github.com/jjohannes/missing-metadata-guava/commit/deef650a12e8a7db684408b047959785ad1faaab)

Do you use version `0.3` of this plugin @LouisCAD?

In any case I found a small thing with `30.1.1` and I wanted to add support for the new "jvm-environment" attribute introduced in Gradle 7.0. So I might release a "0.4" soon.

**Comment by jjohannes** [comment]
`0.4` is out. Please give it a try.
